# -*- coding: utf-8 -*-
"""aula06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RO591a8bAJfROyhzVPUGXCJYqL5yV9XY
"""

# 7 indices

# lista = [1,3,5,6,5,5,3,4,8,9,10, "casa", 2,8, "true"]
# lista.append(2)
# lista.append("leandro")
# print(lista)

# Lista 02

# lista02 = [1,3,5,7,10,9,8,5,2, "casa"]
# lista02.remove(10)
# print(lista02)

# Lista 03

# lista03 = [1,3,5,7,10,9,8,5,2, "casa"]
# del lista03[2]
# print(lista03)

# Lista 04

# lista04 = [1,3,5,7,10,9,8,5,2, "casa"]
# lista = len(lista04)
# print(lista)

# Lista 05

# lista05 = [1,3,45,89,35,45,13]
# for i in lista05:
#   print(i)

# Exercícios aula 06

# Exercicio 1 Crie uma lista chamada numeros que contenha os números inteiros de 1 a 5 e imprima-a na tela.

lista = [1,2,3,4,5]
for i in lista:
   print (i)

# Exercício 2: Acesse e imprima o terceiro elemento da lista numeros

# lista02 = [1,2,3,4,5]
# print(lista[3])

# Exercício 3: Adicione o número 6 à lista numeros e imprima a lista atualizada.

# lista3 = [1,3,5,7,10,9,8,5,2, "casa"]
# lista3.append(6)
# print(lista3)

# Exercício 4: Remova o número 3 da lista numeros e imprima a lista resultante

# lista4 = [1,3,5,7,10,9,8,5,2, "casa"]
# lista4.remove(3)
# print(lista4)

# Exercício 5: Crie uma lista chamada frutas contendo três nomes de frutas diferentes. Em seguida, concatene essa lista com a lista numeros e imprima o resultado.

# listafrutas = ["jaca", "amora", "pimentao", "brocolis"]
# listanumeros = [1,2,3,4,5,6,7]
# print(listafrutas + listanumeros)

# Exercício 6: Use um loop for para percorrer e imprimir todos os elementos da lista frutas.
# for i in listafrutas:
#  print(i)

# Exercicio 7: Verifique se o número 5 está presente na lista numeros e imprima uma mensagem , informando se ele está na lista ou não.

# listanumeros = [1,2,3,4,5,6,7]
# if 5 in listanumeros:
#   print("O numero 5 esta na lista")
# else:
#   print("O numero 5 não esta na lista")